[project]
name = "message-feed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aio-pika>=9.5.8",
    "telethon>=1.42.0",
    "PySocks>=1.7.1",
]
